SET FOREIGN_KEY_CHECKS = 0;
drop table  ingredient;
drop table  product;
drop table  premade_menu;
drop table  premade_menu_product;
drop table  product_ingredient;
drop table  order_item;
drop table  customer_order;
drop table  customer_order_items;
drop table  allowed_menu_products;
SET FOREIGN_KEY_CHECKS = 1;