    insert into product values (1,'McWrap Chicken',4);
        insert into product_ingredient values (1,1,3);
        insert into product_ingredient values (1,2,1);
        insert into product_ingredient values (1,3,3);
    insert into product values (2,'mcWrap Veggie',3);
        insert into product_ingredient values (2,2,1);
        insert into product_ingredient values (2,3,1);
    insert into product values (3,'McWrap Chicken Small',2);
        insert into product_ingredient values (3,1,2);
        insert into product_ingredient values (3,4,1);
        insert into product_ingredient values (3,3,2);
insert into premade_menu values (1,'Happy Meal',4);
    insert into product values (5,'McFish',4);
        insert into product_ingredient values(5,5,1);
        insert into product_ingredient values(5,6,1);
        insert into product_ingredient values(5,7,1);
        insert into product_ingredient values(5,8,1);
    insert into product values (6,'Hamburger',2);
        insert into product_ingredient values(6,9,1);
        insert into product_ingredient values(6,10,1);
        insert into product_ingredient values(6,11,1);
        insert into product_ingredient values(6,12,1);
    insert into product values (7,'Cheeseburger',2.5);
        insert into product_ingredient values(7,9,1);
        insert into product_ingredient values(7,10,1);
        insert into product_ingredient values(7,11,1);
        insert into product_ingredient values(7,76,1);
        insert into product_ingredient values(7,13,1);
    insert into product values (8,'Chicken McNuggets Small',2);
        insert into product_ingredient values(8,14,4);
    insert into product values (9,'Veggy McNuggets Small',2);
        insert into product_ingredient values(9,15,4);
    insert into product values (10,'Fries Small',2);
        insert into product_ingredient values(10,16,1);
    insert into product values (11,'Carrots Small',0.5);
        insert into product_ingredient values(11,17,1);
            insert into premade_menu_product values (1,11);
    insert into product values (12,'Soft Drink Cola 25 cl.',1);
        insert into product_ingredient values(12,18,1);
    insert into product values (13,'Soft Drink Cola Zero 25 cl.',1);
        insert into product_ingredient values(13,19,1);
    insert into product values (14,'Soft Drink Cola Light 25 cl.',1);
        insert into product_ingredient values(14,20,1);
    insert into product values (15,'Soft Drink Sprite 25 cl.',1);
        insert into product_ingredient values(15,21,1);
    insert into product values (16,'Soft Drink Fanta 25 cl.',1);
        insert into product_ingredient values(16,22,1);
    insert into product values (17,'Drink Apple Juice 25 cl.',1);
        insert into product_ingredient values(17,23,1);
    insert into product values (18,'Drink Orange Juice 25 cl.',1);
        insert into product_ingredient values(18,24,1);
    insert into product values (19,'Drink Water 25 cl.',1);
        insert into product_ingredient values(19,25,1);
    insert into product values (20,'Drink Sparkling Water 25 cl.',1);
        insert into product_ingredient values(20,26,1);
    insert into product values (21,'Drink Fristi',1);
        insert into product_ingredient values(21,27,1);
    insert into product values (22,'Petit Lu',0.5);
        insert into product_ingredient values(22,28,1);
    insert into product values (23,'IceCream Cone',0.5);
        insert into product_ingredient values(23,29,1);
    insert into product values (24,'Ice Squeeze',0.5);
        insert into product_ingredient values(24,30,1);
    insert into product values (25,'Fresh Pineapple Chunks',0.5);
        insert into product_ingredient values(25,31,1);
    insert into product values (26,'Acimel',0.5);
        insert into product_ingredient values(26,32,1);
    insert into product values (27,'Danonino',0.5);
        insert into product_ingredient values(27,33,1);
insert into premade_menu values (2,'Medium Menu',6);
    insert into product values (28,'Medium French Fries',1.5);
        insert into product_ingredient values(28,34,1);
    insert into product values (29,'Medium Mixed Salad',2);
        insert into product_ingredient values(29,35,1);
    insert into product values (30,'Drink Water Vittel 33 cl.',1.5);
        insert into product_ingredient values(30,36,1);
    insert into product values (31,'Drink Water Perrier 33 cl.',1.5);
        insert into product_ingredient values(31,37,1);
    insert into product values (32,'Drink Tropicana Orangejuice',2);
        insert into product_ingredient values(32,38,1);
    insert into product values (33,'Drink Cola 33 cl.',1.5);
        insert into product_ingredient values(33,39,1);
    insert into product values (34,'Drink Cola Zero 33 cl.',1.5);
        insert into product_ingredient values(33,40,1);
    insert into product values (35,'Drink Cola Light 33 cl.',1.5);
        insert into product_ingredient values(34,41,1);
    insert into product values (36,'Drink Sprite 33 cl.',1.5);
        insert into product_ingredient values(35,42,1);
    insert into product values (37,'Drink Fanta 33 cl.',1.5);
        insert into product_ingredient values(37,43,1);
insert into premade_menu values (3,'Large Menu',8);
    insert into product values (38,'Large French Fries',2);
        insert into product_ingredient values(38,44,1);
    insert into product values (39,'Large Mixed Salad',2);
        insert into product_ingredient values(39,45,1);
    insert into product values (40,'Drink Water Vittel 50 cl.',1.5);
        insert into product_ingredient values(40,46,1);
    insert into product values (41,'Drink Water Perrier 50 cl.',1.5);
        insert into product_ingredient values(41,47,1);
    insert into product values (42,'Drink Tropicana Orangejuice 50 cl.',2);
        insert into product_ingredient values(42,48,1);
    insert into product values (43,'Drink Cola 50 cl.',1.5);
        insert into product_ingredient values(43,49,1);
    insert into product values (44,'Drink Cola Zero 50 cl.',1.5);
        insert into product_ingredient values(44,50,1);
    insert into product values (45,'Drink Cola Light 50 cl.',1.5);
        insert into product_ingredient values(45,51,1);
    insert into product values (46,'Drink Sprite 50 cl.',1.5);
        insert into product_ingredient values(46,52,1);
    insert into product values (47,'Drink Fanta 50 cl.',1.5);
        insert into product_ingredient values(47,53,1);
insert into premade_menu values (4,'Salads Menu',6);
    insert into product values (48,'Cheese and Bacon Salad',4.5);
        insert into product_ingredient values(48,54,1);
    insert into product values (49,'Pesto and Mozzarella Salad',4.5);
        insert into product_ingredient values(49,55,1);
    insert into product values (50,'Ceasar Salad',5);
        insert into product_ingredient values(50,56,1);
    insert into product values (51,'Irresistible don Juan',8);
        insert into product_ingredient values(51,57,1);
        insert into product_ingredient values(51,58,2);
        insert into product_ingredient values(51,59,1);
        insert into product_ingredient values(51,60,1);
        insert into product_ingredient values(51,61,1);
        insert into product_ingredient values(51,62,1);
        insert into product_ingredient values(51,63,1);
    insert into product values (52,'Meastro generous Jack',4);
        insert into product_ingredient values(52,58,2);
        insert into product_ingredient values(52,64,2);
        insert into product_ingredient values(52,65,1);
        insert into product_ingredient values(52,66,1);
        insert into product_ingredient values(52,67,1);
        insert into product_ingredient values(52,63,1);
        insert into product_ingredient values(52,68,2);
        insert into product_ingredient values(52,69,1);
    insert into product values (53,'Meastro generous Jaqueline',4);
        insert into product_ingredient values(53,70,2);
        insert into product_ingredient values(53,64,2);
        insert into product_ingredient values(53,65,1);
        insert into product_ingredient values(53,71,1);
        insert into product_ingredient values(53,68,2);
        insert into product_ingredient values(53,69,1);
    insert into product values (54,'Big Mac',3.5);
        insert into product_ingredient values(54,72,1);
        insert into product_ingredient values(54,58,2);
        insert into product_ingredient values(54,73,2);
        insert into product_ingredient values(54,74,2);
        insert into product_ingredient values(54,11,3);
        insert into product_ingredient values(54,71,1);
        insert into product_ingredient values(54,75,1);
    insert into product values (55,'Double Cheese',2.5);
        insert into product_ingredient values(55,58,2);
        insert into product_ingredient values(55,9,1);
        insert into product_ingredient values(55,11,2);
        insert into product_ingredient values(55,76,1);
        insert into product_ingredient values(55,77,1);